### ISSUE TITLE
Invalid type name in commands.lua

### ISSUE THREAD

**Issue by zeitchef** [jedrzejboczar/possession.nvim#1]
Looks promising, but something is throwing an error:

![Screen Shot 2022-04-03 at 21 05 20](https://user-images.githubusercontent.com/6670659/161444160-2ce033e0-5f43-4ffa-abe4-b271bf861352.jpg)

**Comment by jedrzejboczar** [comment]
Hmm, looks like the following line is an error:
```lua
vim.validate { candidates = { candidates, { 'table', 'function' } } }
```
Which version of Neovim are you using? Could it be that in some older versions it was not possible to specify multiple types for an argument in `vim.validate` (here: table/function)?

**Comment by jedrzejboczar** [comment]
Just to make sure, the error is thrown when you try to complete a command, right?

**Comment by zeitchef** [comment]
I'm running version 0.6.1

> Just to make sure, the error is thrown when you try to complete a command, right?

Correct

**Comment by jedrzejboczar** [comment]
Ah, it seems it changed: https://github.com/neovim/neovim/commit/55c4393e9f80ac3e7233da889efce4f760e41664.
That form is convenient, but it would be nice to at least support latest stable, so I'll try to fix this in a moment, shouldn't be too much work.

**Comment by jedrzejboczar** [comment]
Should be fixed with https://github.com/jedrzejboczar/possession.nvim/commit/0e16b87ae2ed51797ba6ffc9f2638411c61d71ad.
We'll see if there is more incompatibility with stable Neovim, but I hope the code should mostly be compatible.

**Comment by zeitchef** [comment]
Seems to work, but I'm having a number of other issues. I'll file issues for these in turn. Thanks for your responsiveness!
