### ISSUE TITLE
How do I create a session?

### ISSUE THREAD

**Issue by melkster** [jedrzejboczar/possession.nvim#10]
Hi! I'm trying this plugin out but got stuck immediately. I want to save the current session, but running `:PossessionSave` prints the error "No session is currently open". Is that the intended behaviour? Since I don't yet have any sessions I can't open one.

This is my config:

```lua
use {
  'jedrzejboczar/possession.nvim',
  requires = { 'nvim-lua/plenary.nvim' },
  config = function()
    require('possession').setup()
  end
}
```

**Comment by melkster** [comment]
I realized just after posting this that that I'm supposed to add a session name as an argument to `:PossesionSave`, e.g. `PossesionSave session_name`. Perhaps the command should prompt the user for a session name using `vim.ui.input` if no session is open and no argument is provided?

**Comment by jedrzejboczar** [comment]
Yeah, looks like the message is not very helpful... When I find a moment I'll try to improve the message or use `vim.ui.input` as you suggested.

**Comment by jedrzejboczar** [comment]
I updated the message in https://github.com/jedrzejboczar/possession.nvim/commit/893479c418a4261261fce2492b1782ac031f19f9.
