### ISSUE TITLE
Show session name in lualine?

### ISSUE THREAD

**Issue by toddknutson** [jedrzejboczar/possession.nvim#14]
Is there a way to show the current session name in a lualine section?

It seems like I would need to create a [custom lualine component](https://github.com/nvim-lualine/lualine.nvim#custom-components) that returns the Possession session name as a string. It seems like I could get the session name from [this function](https://github.com/jedrzejboczar/possession.nvim/blob/bdb7a99c4180bd6a45da1165e51fc31948412241/lua/possession/query.lua#L10), but I'm not sure how to do that exactly. Any help would be appreciated! Thanks for a great plugin!

**Comment by jedrzejboczar** [comment]
Hi, the following should do the job:
```lua
local function session_name()
    return require('possession.session').session_name or ''
end
```

**Comment by toddknutson** [comment]
Thanks so much @jedrzejboczar! This works perfect!! 

For anyone else coming across this, I simply copied the suggested function (above) to my lualine config and then referenced the function name within the lualine setup. For example:

```
lualine.setup {
  sections = { lualine_a = { session_name } }
}
```

**Comment by toddknutson** [comment]
Update: This change, https://github.com/jedrzejboczar/possession.nvim/pull/53, causes an issue with the config described above. It's a simple fix. Change the lualine config to be something like this:

```
local function my_session_name()
    return require('possession.session').get_session_name() or ''
end

lualine.setup {
  sections = { lualine_a = { my_session_name } }
}
```

**Comment by jedrzejboczar** [comment]
Thanks for noting, it's also updated in README: https://github.com/jedrzejboczar/possession.nvim?tab=readme-ov-file#statusline
