### ISSUE TITLE
No fold found Error

### ISSUE THREAD

**Issue by gj86** [jedrzejboczar/possession.nvim#19]
When restoring session, the below error happens time to time. Not always.
```lua
E5108: Error executing lua ...ck/packer/opt/possession.nvim/lua/possession/session.lua:176: Vim(normal):E490: No fold found
stack traceback:
	[C]: in function 'nvim_exec'
	...ck/packer/opt/possession.nvim/lua/possession/session.lua:176: in function 'fn'
	...possession.nvim/lua/telescope/_extensions/possession.lua:77: in function 'run_replace_or_original'
	...k/packer/opt/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
	...ack/packer/opt/telescope.nvim/lua/telescope/mappings.lua:341: in function 'execute_keymap'
	[string ":lua"]:1: in main chunk
```
My session options
```lua
vim.opt.sessionoptions =
	{ 'buffers', 'curdir', 'folds', 'help', 'tabpages', 'globals', 'winsize', 'winpos', 'terminal' }
```

**Comment by jedrzejboczar** [comment]
I tried to reproduce the issue but could not. I don't think it's related to this plugin specifically, I would rather say it might be related to `:mksession` and your folding configuration. It seems like something is trying to open a fold that is no longer valid (e.g. lines in the file have been deleted). Are you creating folds manually using `zf`? If not then I would suggest removing `folds` from sessionoptions, maybe this would help.

**Comment by gj86** [comment]
It mostly occurs when loading session using `:Telescope possession list` or `:PossessionLoad mysession`, but loading the same session using `:PossessionLoad` without any session name (load last session) the error does not occur.

**Comment by casio** [comment]
Fyi I was seeing the same issue and removing `folds` from `vim.opt.sessionoptions` seems to have solved it for me 👍

**Comment by jedrzejboczar** [comment]
Thanks for info, I think I can close this issue.

**Comment by piotr-marendowski** [comment]
For anyone still experiencing this issue after removing `folds` try adding:
```
vim.api.nvim_create_autocmd({ "BufEnter" }, {
    pattern = { "*" },
    command = "normal zx",
})
```
This worked for me.
From [this issue on Telescope](https://github.com/nvim-telescope/telescope.nvim/issues/699#issuecomment-1159637962)

**Comment by svonjoi** [comment]
> For anyone still experiencing this issue after removing `folds` try adding:
> 
> ```
> vim.api.nvim_create_autocmd({ "BufEnter" }, {
>     pattern = { "*" },
>     command = "normal zx",
> })
> ```
> 
> This worked for me. From [this issue on Telescope](https://github.com/nvim-telescope/telescope.nvim/issues/699#issuecomment-1159637962)

this omit the error but after delete file in neotree plugin it folds all
