### ISSUE TITLE
:PossessionSave only saves session after root directory

### ISSUE THREAD

**Issue by zeitchef** [jedrzejboczar/possession.nvim#2]
Perhaps I'm not understanding exactly, but I would expect `:PossessionSave` to save a session with the name of the current directory, not the root directory.

![Screen Shot 2022-04-03 at 22 33 24](https://user-images.githubusercontent.com/6670659/161447418-cbe56bfe-95c9-48e2-9794-fa8864054ca6.jpg)

Currently, this is the only session file it will create.

When I dismiss the message, I get the following error:

![Screen Shot 2022-04-03 at 22 36 17](https://user-images.githubusercontent.com/6670659/161447510-3ca8e9d6-6b86-467b-9c04-06a057be5516.jpg)

Edit: After actually looking at the commands, I realize this requires an argument. However, when saving the session, all open buffers are closed. Very weird.

I was hoping this would be essentially a drop-in replacement for `auto-sessions` which basically just manages the sessions for me. I don't want to have to type commands or use Telescope to load a session every time. If in the future, `Possession` will just work out of the box like `auto-session` I'll be happy to have another look!

**Comment by jedrzejboczar** [comment]
Well, the interface in auto-session is a bit different from what I can see. With auto-session your session name is the current directory name. In possession when you invoke `PossessionSave {name}` you would use a descriptive name for this project (`PossessionSave my-project`) and the file is stored under `session_dir` (can be changed in `setup`). CWD will be stored in the file contents (not in file name). 

Anyway, currently there is no feature for automatic session save/restore. I might add it in near future, as it seems like a nice feature to have, though I generally prefer explicitly specifying which session I want to load.

I opened https://github.com/jedrzejboczar/possession.nvim/issues/3 and will close this issue.
