### ISSUE TITLE
Invalid window id on saving

### ISSUE THREAD

**Issue by przepompownia** [jedrzejboczar/possession.nvim#20]
Hi, 

I check if Possession can be useful for me. 

Probably (maybe not only) we need `nvim_win_is_valid` inside loop in https://github.com/jedrzejboczar/possession.nvim/blob/master/lua/possession/plugins/close_windows.lua#L38 

I tried to see how saving behaves when [DBUI](https://github.com/kristijanhusak/vim-dadbod-ui) is open with the query result and [Noice](https://github.com/folke/noice.nvim) is enabled and got
```
   Error  02:22:23 msg_show.lua_error   PossessionSave! dim E5108: Error executing lua ...possession.nvim/lua/possession/plugins/close_windows.lua:7: Invalid window id: 1476
stack traceback:
	[C]: in function 'nvim_win_get_config'
	...possession.nvim/lua/possession/plugins/close_windows.lua:7: in function 'is_floating'
	...possession.nvim/lua/possession/plugins/close_windows.lua:39: in function 'fn'
	...rged/opt/possession.nvim/lua/possession/plugins/init.lua:110: in function <...rged/opt/possession.nvim/lua/possession/plugins/init.lua:109>
	...rged/opt/possession.nvim/lua/possession/plugins/init.lua:59: in function 'call_plugin'
	...rged/opt/possession.nvim/lua/possession/plugins/init.lua:67: in function 'before_save'
	.../unmerged/opt/possession.nvim/lua/possession/session.lua:68: in function 'save'
	...unmerged/opt/possession.nvim/lua/possession/commands.lua:61: in function 'save'
	[string ":lua"]:1: in main chunk
```
Config:
```lua
require('possession').setup {
  plugins = {
    nvim_tree = false,
    delete_hidden_buffers = false,
  },
}
```
Can you reproduce this bug?

I set `close_windows = false,` while it occurs for me.

**Comment by jedrzejboczar** [comment]
@przepompownia Could you please check if https://github.com/jedrzejboczar/possession.nvim/pull/21 fixes the issue? I don't use DBUI and it looks like it requires a lot of setup, I also don't use Noice, so it's a lot easier for me if you could check this on your side. And I think that adding protected call (`pcall`) when closing windows should be a good idea anyway.

**Comment by przepompownia** [comment]
@jedrzejboczar yes, silent closing is a fix. 

In the meantime I wrote [something](https://github.com/przepompownia/nvim-arctgx/blob/103193a9787ff012b2914f7044e143d38bc75208/plugin/session.lua#L5) simpler, which I think will be enough for me at the moment (it's still possible to attach it to Possession hooks). Regardless, thanks - it would be good to merge #21.
