### ISSUE TITLE
Automatic session save/restore

### ISSUE THREAD

**Issue by jedrzejboczar** [jedrzejboczar/possession.nvim#3]
As noted in https://github.com/jedrzejboczar/possession.nvim/issues/2, it would be nice to have this kind of functionality built-in. 

Currently one could use the provided API to do this in their config: [list avaliable sessions](https://github.com/jedrzejboczar/possession.nvim/blob/0e16b87ae2ed51797ba6ffc9f2638411c61d71ad/lua/possession/session.lua#L216) and compare `sessions[X].cwd` to current working directory to select the session we want. 

Adding this feature to the plugin would require some configuration options like:
* should be enabled by a config option (disabled by default) 
* do we want to match CWD exactly, or if opening Vim in `/dir/a/b` session with cwd `/dir/a` should be used?
* or should we actually load the previously open session and not care about cwd whatsoever?
* when to auto-save the session?
* config option for enabling this could be a boolean or a user function that returns a boolean - this can offload some more logic to users

**Comment by RaafatTurki** [comment]
I agree with exact matching

**Comment by jedrzejboczar** [comment]
With https://github.com/jedrzejboczar/possession.nvim/pull/7 by @wasden already merged, automatic save functionality should work without issues.
As for auto restore, I hope I will implement it somewhere soon.

> Even now, when doing `PossessionLoad` without passing a name, I would intuitively expect it to load the session according to `cwd` and not the last general session.

Yeah, I already noticed that the last general session is problematic, especially when opening two Neovim instances, because they will be overwriting the last session of each other. This is especially annoying for `PossessionSave`, so I think I will change the behavior (at the very least for save) when I find time to work on the restore function.

**Comment by aaditeynair** [comment]
Any updates on this?

**Comment by aaditeynair** [comment]
I'll try to do when I get some free time.

**Comment by jedrzejboczar** [comment]
Partially resolved, continued in https://github.com/jedrzejboczar/possession.nvim/issues/45#issuecomment-1817597856
