### ISSUE TITLE
Feature request: `:PossessionRename`

### ISSUE THREAD

**Issue by mawkler** [jedrzejboczar/possession.nvim#31]
I think it would be neat if we had a `:PossessionRename` command that changes the name of a session.

The user would type `:PossessionRename <session name>` and a `vim.ui.input` prompt would pop asking for the new name.

**Comment by jedrzejboczar** [comment]
Implemented in https://github.com/jedrzejboczar/possession.nvim/commit/55b9f52b145169e060fb3a78b60568fb6f6c9bd1.
