### ISSUE TITLE
Sort sessions by modification date in Telescope

### ISSUE THREAD

**Issue by maxigaz** [jedrzejboczar/possession.nvim#32]
It would be great to have the ability to have a sorted list of the session files in Telescope so that the ones that were saved or updated recently are shown at the bottom.

**Comment by jedrzejboczar** [comment]
Nice idea. You can check https://github.com/jedrzejboczar/possession.nvim/pull/33.  This affects only the "initial" sort order, before any fuzzy matching (it probably makes no sense to modify the fuzzy matching sort anyway).

To use the old sorting behaviour use e.g.
```lua 
vim.keymap.set('n', your_map, function()
    require('telescope').extensions.possession.list { sort = 'name' }
end)
```
