### ISSUE TITLE
[Feature] Add mappings to telescope extension

### ISSUE THREAD

**Issue by Fabian-programmer** [jedrzejboczar/possession.nvim#34]
Hey, thank you for your plugin.

I really like the telescope extension. It would be really nice to add a key for deleting and renaming a listed item.

As far as I understand the code it only loads the current selected item by <CR>.

**Comment by Fabian-programmer** [comment]
So I did sth :)

Please have a look at:
https://github.com/Fabian-programmer/possession.nvim/commit/56e7255fb3d795d4eda8c8438d796987628c8b05

I'm using other default formatting...

Now delete session and rename session pops up, when you press ? in normal mode:

![grafik](https://github.com/jedrzejboczar/possession.nvim/assets/65787013/dde05409-b261-479c-ab00-319c171f3748)

Feel free to adapt the solution / make it nicer / etc..

**Comment by jedrzejboczar** [comment]
Thanks! I probably won't have time to work on it this week, but I'll try to take a look next week, as this seems like a nice addition.

**Comment by jedrzejboczar** [comment]
@Fabian-programmer I created https://github.com/jedrzejboczar/possession.nvim/pull/36 with some tweaks to your code. It should make no breaking changes for users, but you should be able to configure it to behave as your version using `telescope.list.mappings` in setup. Could you give it a try?

**Comment by jedrzejboczar** [comment]
You mean the popup `Overwrite session "tmp"? [y/N] `? For me this starts in insert mode both when using `<c-x>` (default mapping) from normal/insert mode. Maybe it has something to do with your `vim.ui.input` implementation? Seems like I'm using some custom implementation based on nui.nvim:

<details>
<summary>vim.ui.input code</summary>

```lua
local function ui_input(opts, on_confirm)
    local Input = require('nui.input')
    local event = require('nui.utils.autocmd').event

    -- FIXME: vim.lsp.buf.rename does not allow to disable the "New Name" prompt...
    if opts.prompt == 'New Name: ' then
        opts.prompt = nil
    end

    -- Calculate size to always have some space after prompt
    local min_size = 30
    local min_space = 20
    local max_size = vim.o.columns - 2
    local default_size = opts.default and #opts.default or 0
    local prompt_size = opts.prompt and #opts.prompt or 0
    local size = math.min(math.max(prompt_size + default_size + min_space, min_size), max_size)

    local popup_opts = {
        relative = 'cursor',
        position = { row = 1, col = 0},
        size = size,
        border = {
            style = 'rounded'
        },
        -- win_options = {
        --     winhighlight = 'Normal:Normal',
        -- }
    }

    local input = Input(popup_opts, {
        prompt = opts.prompt,
        default_value = opts.default,
        on_close = on_confirm,  -- nil as 1st arg
        on_submit = on_confirm,  -- typed value as 1st arg
        -- on_change
    })

    input:mount()

    input:map('n', 'q', input.input_props.on_close, { noremap = true })
    input:map('n', '<esc>', input.input_props.on_close, { noremap = true })

    -- Make sure to disable text wrapping
    vim.api.nvim_buf_set_option(input.bufnr, 'textwidth', 0)

    input:on(event.BufLeave, function()
        input:unmount()
    end)
end

vim.ui.input = ui_input
```

</details>

**Comment by Fabian-programmer** [comment]
Yes, exactly that popup, I didn't remember it 100% when I wrote the comment :).

The strange thing is, rename or delete starts for me in Insert mode. Just not save.
The only plugin I use, which tampers with vim.ui.input should be dressing.

Maybe it just has to do with my config. but anyway the key is not interesting for me 😄 

```
{
		"stevearc/dressing.nvim",
		lazy = true,
		init = function()
			---@diagnostic disable-next-line: duplicate-set-field
			vim.ui.select = function(...)
				require("lazy").load({ plugins = { "dressing.nvim" } })
				return vim.ui.select(...)
			end
			---@diagnostic disable-next-line: duplicate-set-field
			vim.ui.input = function(...)
				require("lazy").load({ plugins = { "dressing.nvim" } })
				return vim.ui.input(...)
			end
		end,
	},
```

**Comment by jedrzejboczar** [comment]
> The strange thing is, rename or delete starts for me in Insert mode. Just not save.

That's strange, maybe it has to do with some key bindings because save/delete should use exactly the same code.

Anyway, it seems like a minor issue so I'll merge this.
