### ISSUE TITLE
Issue with telescope configuration/Option to turn off the telescope previewer

### ISSUE THREAD

**Issue by piotr-marendowski** [jedrzejboczar/possession.nvim#42]
It would be nice to have that option, to make it look more like the [project.nvim](https://github.com/ahmedkhalf/project.nvim). I tried to make it, but it seems that my new option `previewer` (and any telescope option) isn't "connected" to my configuration lua file, but its default variables work. Here's what I did (all in `~/.local/share/nvim/lazy/possession/lua/`):
<details><summary>possesion/config.lua</summary>

```
...
list = {
    previewer = true,
    default_action = 'load',
...
```

</details>
<details><summary>possesion/telescope.lua</summary>

```
... -- added previewer field in list
---@field sort? boolean|possession.QuerySortKey sort the initial sessions list, `true` means 'mtime'
---@field previewer? boolean enable or disable preview

---@param opts possession.TelescopeListOpts
function M.list(opts)
    opts = vim.tbl_extend('force', {
        default_action = 'load',
        sessions = nil,
        sort = 'mtime',
        previewer = true,
    }, opts or {})
...
-- in same function in: pickers.new(opts, { ...
    sorter = conf.generic_sorter(opts),
    previewer = opts.previewer and session_previewer() or false,
    attach_mappings = function(prompt_buf, map)
...
```

</details>
<details><summary>~/.config/nvim/lua/plugins/sessions.lua</summary>

```
...
    telescope = {
        list = {
            previewer = false,
            default_action = 'delete',
        }
    }
...
```

</details>

This always displays previewer (even if I specified otherwise) and `default_action` doesn't work either. So maybe I do something wrong or as I said before telescope configuration isn't accessible from plugin's configuration (by mistake I also pasted telescope's configuration (`previewer = false` etc.) in telescope's extensions configuration and they also don't work there).

**Comment by jedrzejboczar** [comment]
Does the following do the job? (without any changes to current possession code)
```lua
require('telescope').extensions.possession.list { previewer = false }
```
For me this gives similar results to the screenshot from project.nvim, but there is no cwd after session name.
