### ISSUE TITLE
Error when invoking PossessionShow function

### ISSUE THREAD

**Issue by gj86** [jedrzejboczar/possession.nvim#51]
The commit d4a071e26ba49d147c6ceaa7fe209d6c6e5d10fd causes this issue when calling function `PossessionShow`
```lua
Error executing Lua callback: vim/shared.lua:0: s: expected string, got table
stack traceback:
	[C]: in function 'error'
	vim/shared.lua: in function 'validate'
	vim/shared.lua: in function 'endswith'
	...share/nvim/lazy/possession.nvim/lua/possession/paths.lua:11: in function 'session'
	...re/nvim/lazy/possession.nvim/lua/possession/commands.lua:127: in function 'show'
	...local/share/nvim/lazy/possession.nvim/lua/possession.lua:33: in function <...local/share/nvim/lazy/possession.nvim/lua/possession.lua:32>
```

Downgrading plugin to bfef005ac08ad101cc5ec1d3dec67d9a785bf5a2 commit fixes this for now.

**Comment by jedrzejboczar** [comment]
Thanks, could you please verify that https://github.com/jedrzejboczar/possession.nvim/pull/53 fixes the issue?

**Comment by gj86** [comment]
> Thanks, could you please verify that #53 fixes the issue?

Sorry for very late reply. I have manually applied the PR and yes, it fixes the issue.

Thank you for fixing the issue so fast.
