### ISSUE TITLE
bug: auto load cwd with auto save will save blank session first

### ISSUE THREAD

**Issue by josh-nz** [jedrzejboczar/possession.nvim#60]
Relates to #55 

If configured with `autosave.cwd = true` and `autoload.cwd = true`, when starting Neovim `M.load` in `session.lua` will try to autosave. It looks like this should be skipped but for whatever reason, `autosave_skip()` is returning true for me.

This has the follow behaviour:
1. The `cwd` json file is parsed first, so session data is in memory.
2. The `cwd` session is loaded, triggering autosave
3. autosave saves the blank Neovim buffers into the `cwd` session file
4. session is loaded from data in memory.

While this works, if you have other autosave settings turned off (or Neovim crashes etc), then there is a chance the session will be lost.

Ideally, we skip saving when autoloading from `cwd`. It looks like this was the intent, and `autosave_skip()` has a bug. I don't know the nuance of Neovim that the skip function is trying to achieve, but results from my tests are below:

<img width="360" alt="Screen Shot 2024-06-11 at 18 56 29" src="https://github.com/jedrzejboczar/possession.nvim/assets/414204/5cfa491c-d812-4d4d-a3ca-4d83eba1d0d2">

```lua
local function autosave_skip()
    -- Skip scratch buffer e.g. startscreen
    local unscratch_buffers = vim.tbl_filter(function(buf)
        return 'nofile' ~= vim.bo[buf].buftype
    end, vim.api.nvim_list_bufs())
    -- unscratch_buffers is true
    -- next(unscratch_buffers) is true
    -- so return evaluates to false
    return not unscratch_buffers or not next(unscratch_buffers)
end
```

**Comment by jedrzejboczar** [comment]
Fixed in https://github.com/jedrzejboczar/possession.nvim/pull/55
