### ISSUE TITLE
Bug: Sessions can be lost if there is a Possession error during load

### ISSUE THREAD

**Issue by josh-nz** [jedrzejboczar/possession.nvim#67]
If for some reason Possession cannot load a session during Neovim start, and `autosave.cwd` or `autosave.tmp` is configured, when exiting Neovim, these files will be overwritten, potentially losing session data.

I don't think this is so much of a problem for `tmp` since the name implies it is temporary. But I not sure that the `cwd` session should be overwritten.

I wonder if it might be worthwhile to set a global flag on error, and if this is set, do not autosave.

I'm not sure how common this scenario will be. I ran across it during development of #63 in part due to bugs. The situation where I think this could be most likely is with a custom autoload function returning something invalid. This however gets complicated because the user could manually start a `cwd` session, in which case autosave should probably be enabled again?

Maybe it is satisfactory enough to just document the current risk.

**Comment by jedrzejboczar** [comment]
You mean the following scenario?
1. Start Neovim in dirA
2. on VimEnter possession tries to load a cwd session for dirA
3. loading fails for some reason
4. user quits
5. autosave cwd triggers and overwrites the old session

I am not sure if we can handle it well. We could set a flag to disable autsave if autoload failed. But if loading fails than there was some issue with the session, so overwriting it should fix the problem. And even after a bug user could have opened some files and continued with their normal work, then they would expect that autosave happens.

What we might consider is maybe some kind of session backup if loading fails? This way users would be able to at least examine the buggy session. 

But I am not sure what would be the best solution.

**Comment by josh-nz** [comment]
Your listed scenario is correct. I think that if load fails due to corrupt JSON, overwriting it is fine. I think creating backups is probably just unnecessary code to maintain.

As per my original comment, I think the biggest possibility for this loss to occur is when the user has a custom autoload function that errors, or when they are trying to develop and test this function.

I'm also not sure if it's worth trying to do much about. It was just something I ran across so documented it here. At least there will be a note about it if people come searching in the future. 

Happy to have this closed for now. Maybe others can open it later if people actually hit this issue in the real world.
