### ISSUE TITLE
Terminals are not killed because they have "unsaved changes"

### ISSUE THREAD

**Issue by jolars** [jedrzejboczar/possession.nvim#8]
If there is a neovim terminal in a hidden buffer, possession will fail to save the session with the following message:

```
Cannot delete buffer with unsaved changes: "term://[...]"
```

Perhaps terminals should simply be force-killed if they are hidden and the option is set?

**Comment by jedrzejboczar** [comment]
I am not sure if force-killing terminal buffers by default is a good idea, as something important could be running there. Maybe it'd be better to accept a `function(buf) -> bool` to be passed for `deleter_hidden_buffers.force`? Then you could use:
```lua
force = function(buf) return vim.api.nvim_buf_get_option(buf, 'buftype') == 'terminal' end
```
What do you think?

**Comment by jolars** [comment]
Seems reasonable!
________________________________

**Comment by jedrzejboczar** [comment]
Ok, with https://github.com/jedrzejboczar/possession.nvim/commit/3ed843794beeb6baf2557176ccc0d58ce24ba425 this should now be possible.
